// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC087O7xgFqfES-bdswNCttRcCbRFOXFlc',
    appId: '1:226964192727:web:821e4ccc63c22388fc9f92',
    messagingSenderId: '226964192727',
    projectId: 'parkbuddy-31f23',
    authDomain: 'parkbuddy-31f23.firebaseapp.com',
    storageBucket: 'parkbuddy-31f23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ-ajJZxYDMgzQcG8G5tipB6_a6uXXUX4',
    appId: '1:226964192727:android:d2cb0e3bc01d7faafc9f92',
    messagingSenderId: '226964192727',
    projectId: 'parkbuddy-31f23',
    storageBucket: 'parkbuddy-31f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnPbQRc3bltkjgS4jAs7IiHMmKXER6snM',
    appId: '1:226964192727:ios:3aff53ebb679fe5afc9f92',
    messagingSenderId: '226964192727',
    projectId: 'parkbuddy-31f23',
    storageBucket: 'parkbuddy-31f23.appspot.com',
    iosBundleId: 'com.example.plz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnPbQRc3bltkjgS4jAs7IiHMmKXER6snM',
    appId: '1:226964192727:ios:3aff53ebb679fe5afc9f92',
    messagingSenderId: '226964192727',
    projectId: 'parkbuddy-31f23',
    storageBucket: 'parkbuddy-31f23.appspot.com',
    iosBundleId: 'com.example.plz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC087O7xgFqfES-bdswNCttRcCbRFOXFlc',
    appId: '1:226964192727:web:650f4a51ce61af93fc9f92',
    messagingSenderId: '226964192727',
    projectId: 'parkbuddy-31f23',
    authDomain: 'parkbuddy-31f23.firebaseapp.com',
    storageBucket: 'parkbuddy-31f23.appspot.com',
  );

}